DjangoMall/DJMall/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.dadmin.admin import admin_site
from .utils.views import IndexTemplateView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('dadmin/', admin_site.urls),
    path('captcha/', include('captcha.urls')),
    path('product/', include('product.urls')),
    path('users/', include('users.urls')),
    path('personal/', include('personal.urls')),
    path("order/", include('order.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexTemplateView.as_view(), name="index"),
] + static(settings.DOCS_URL , document_root=settings.DOCS_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoMall/apps/personal/urls.py
from django.urls import path, re_path
from .import views

app_name = 'personal'

urlpatterns = [
    path("home/", views.DJMallUserPersonalView.as_view(), name="home"),
    path("username/<int:pk>/update/", views.DJMallUserUpdateView.as_view(), name="update_username"),
    path("email/<int:pk>/update/", views.DJMallUserUpdateEmailView.as_view(), name="update_email"),
    path('fav_list/', views.DJMallFavoriteListView.as_view(), name='fav_list'),
    path("fav_delete/<int:pk>/", views.DJMallFavoriteDeleteView.as_view(), name="fav_delete"),
    path("address/list/", views.DJMallAddressListView.as_view(), name="address_list"),
    path("address/create/", views.DJMallAddressCreateView.as_view(), name="address_create"),
    path("address/update/<int:pk>/", views.DJMallAddressUpdateView.as_view(), name="address_update"),
    path("address/delete/<int:pk>/", views.DJMallAddressDeleteView.as_view(), name="address_delete"),
    path("address/update/<int:pk>/default/", views.DJMallAddressDefaultUpdateView.as_view(), name="address_default_update"),
]

DjangoMall/apps/product/urls.py
from django.urls import path

from .import views

app_name = "product"

urlpatterns = [
    path('category_list/', views.DJMallProductCategoryListView.as_view(), name="category_list"),
    path('category/<int:pk>/', views.DJMallProductCategoryView.as_view(), name="category_detail"),
    path('goods/<int:product_id>/detail/', views.ProductDetailView.as_view(), name="product_goods_detail"),
    path("cart/", views.DJMallShopingCartView.as_view(), name="cart"),
    path("cart/del/<int:pk>/", views.DJMallShopingCartDeleteView.as_view(), name="cart_delete"),
    
]

DjangoMall/apps/users/urls.py
from django.urls import path, include
from .import views

app_name = 'users'

urlpatterns = [
    path("login/", views.DJMallLoginView.as_view(), name="login"),
    path("register/", views.DJMallRegisterView.as_view(), name="register"),
    path('logout/', views.DJMallLogoutView.as_view(), name="logout"),
    path("email/code/", views.DJMallEmailVerifyRecordCreateView.as_view(), name="email_code"),
]

DjangoMall/themes/default/templates/component/head_top.html
<template>
    <nav class="navbar container">
        <div class="navbar-brand">
            <a class="navbar-item">
                <b-icon size="is-small" pack="mdi" icon="star-plus-outline"></b-icon>
                <span>收藏本站</span> 
            </a>
            <span class="navbar-item">欢迎光临本店！</span>
        </div>

        <div class="navbar-menu">
            <div class="navbar-end">
                {% if request.user.is_authenticated %}
                    <b-dropdown
                        v-model="navigation"
                        position="is-bottom-left"
                        append-to-body
                        aria-role="menu">
                        <template #trigger>
                            <a
                                class="navbar-item"
                                role="button">
                                <span>[[ name ]]</span>
                                <b-icon icon="menu-down"></b-icon>
                            </a>
                        </template>
                        <b-dropdown-item custom aria-role="menuitem">
                            欢迎来到 <b>DJMall商城！</b>
                        </b-dropdown-item>
                        <hr class="dropdown-divider">
                        <b-dropdown-item has-link aria-role="menuitem">
                            <a href="{% url 'personal:home' %}" target="_blank">
                                <b-icon icon="home" size="is-small"></b-icon>
                                个人中心
                            </a>
                        </b-dropdown-item>
                        <b-dropdown-item  @click="logout">
                            <b-icon icon="logout" size="is-small"></b-icon>
                            退出
                        </b-dropdown-item>
                    </b-dropdown>
                {% else %}
                <a href="{% url 'users:register' %}" class="navbar-item">
                    <span>注册</span> 
                    <!-- <b-icon size="is-small" pack="mdi" icon="account-plus-outline"></b-icon> -->
                </a> 
                <span class="navbar-item p-0">|</span>
                <a href="{% url 'users:login' %}" class="navbar-item">
                    <span>登录</span> 
                    <!-- <b-icon size="is-small" pack="mdi" icon="login-variant"></b-icon> -->
                </a>
                {% endif %}
                <a href="{% url 'product:cart' %}" class="navbar-item has-background-light pl-4 pr-4">
                    <span class="icon is-small"><i class="mdi mdi-cart-minus"></i></span>
                    <span class="pl-2">购物车(<span v-if='cartNum'>[[ cartNum ]]</span> <i v-else>0</i>)</span> 
                </a>
            </div>
        </div>    
    </nav>
</template>

DjangoMall/themes/default/templates/component/nav.html
<template>
    <b-navbar wrapper-class="container" type="is-primary" transparent spaced>
        <template #brand>
            <b-navbar-item href="/">
                <img src="http://mall.lotdoc.cn/static/users/images/logo.png" 
                    alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
            </b-navbar-item>
        </template>
        <template #start>
            <b-navbar-item href="/" {% if request.path_info == '/' %}active{% endif %}>
                首页
            </b-navbar-item>
            <b-navbar-item href="{% url 'product:category_list' %}" 
                {% if request.path_info == '/product/category_list/' %}active{% endif %}>
                <b-icon
                    pack="mdi"
                    icon="format-list-text"
                    size="is-small">
                </b-icon>
                <span>全部分类</span> 
            </b-navbar-item>
            {% for key, values in category_dict.items %}
            {% if key.is_nav and not values %}
            <b-navbar-item href="{% url 'product:category_detail' key.id %}">
                {{ key.name }}
            </b-navbar-item>
            {% endif %}
            {% if values and key.is_nav %}
            <b-navbar-dropdown label="{{ key }}" hoverable>
                {% for sub_cate in values  %}
                {% if sub_cate.is_nav %}
                <b-navbar-item href="{% url 'product:category_detail' sub_cate.id %}">
                    {{ sub_cate }}
                </b-navbar-item>
                {% endif %}
               
                {% endfor %}
            </b-navbar-dropdown>
            {% endif %}
            {% endfor %}
            
        </template>

        <template #end>
            <b-navbar-item tag="div">
                <b-field>
                    <b-select placeholder="商品">
                        <option>商品</option>
                        <option>文章</option>
                    </b-select>
                    <b-input type="search" placeholder="Search"></b-input>
                    <p class="control">
                        <b-button type="is-danger" label="Search" />
                    </p>
                </b-field>
            </b-navbar-item>
        </template>
    </b-navbar>
</template>

DjangoMall/themes/default/templates/component/page.html
<nav class="pagination is-small" role="navigation" aria-label="pagination">
    {% if page_obj.has_previous %}
    <a class="pagination-previous is-disabled" href="?page={{ page_obj.previous_page_number }}" title="上一页">Previous</a>
    {% endif %}

    {% if page_obj.has_next %}
    <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}

    <ul class="pagination-list">
        {% for page in pages %}
            <li>
                <a class="pagination-link {% if page_obj.number == page %}is-current {% endif %}" aria-label="Goto page 2" aria-current="page" 
                href="?page={{ page }}">
                    {{ page }}
                </a>
            </li>
        {% endfor %}
    </ul>
</nav>