DjangoMall/DJMall/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.dadmin.admin import admin_site
from .utils.views import IndexTemplateView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('dadmin/', admin_site.urls),
    path('captcha/', include('captcha.urls')),
    path('product/', include('product.urls')),
    path('users/', include('users.urls')),
    path('personal/', include('personal.urls')),
    path("order/", include('order.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexTemplateView.as_view(), name="index"),
] + static(settings.DOCS_URL , document_root=settings.DOCS_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoMall/apps/order/urls.py
from django.urls import path, re_path
from .import views

app_name = 'order'

urlpatterns = [
    path("pay/", views.DJMallPayView.as_view(), name="pay"),
    path("orderinfo/", views.DJMallOrderInfoView.as_view(), name="orderinfo")
]

DjangoMall/apps/personal/urls.py
from django.urls import path, re_path
from .import views

app_name = 'personal'

urlpatterns = [
    path("home/", views.DJMallUserPersonalView.as_view(), name="home"),
    path("username/<int:pk>/update/", views.DJMallUserUpdateView.as_view(), name="update_username"),
    path("email/<int:pk>/update/", views.DJMallUserUpdateEmailView.as_view(), name="update_email"),
    path('fav_list/', views.DJMallFavoriteListView.as_view(), name='fav_list'),
    path("fav_delete/<int:pk>/", views.DJMallFavoriteDeleteView.as_view(), name="fav_delete"),
    path("address/list/", views.DJMallAddressListView.as_view(), name="address_list"),
    path("address/create/", views.DJMallAddressCreateView.as_view(), name="address_create"),
    path("address/update/<int:pk>/", views.DJMallAddressUpdateView.as_view(), name="address_update"),
    path("address/delete/<int:pk>/", views.DJMallAddressDeleteView.as_view(), name="address_delete"),
    path("address/update/<int:pk>/default/", views.DJMallAddressDefaultUpdateView.as_view(), name="address_default_update"),
]

DjangoMall/apps/order/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from DJMall.utils.models import DJMallBaseModel
from product.models import DJMallProductSKU
from django.contrib.auth import get_user_model

User = get_user_model()


class DJMallOrderInfo(DJMallBaseModel):
    """订单信息"""

    class PayMethodChoices(models.IntegerChoices):
        CASH = 1, _('货到付款')
        ALIPAY = 2, _('支付宝')
        WECHATPAY = 3, _('微信支付')
        OVERPAY = 4, _('余额支付')

    class OrderStatusChoices(models.IntegerChoices):
        TOBPAY = 1, _('待支付')
        TOBDELIVER = 2, _('待发货')
        TOBRECEIVED = 3, _('待收货')
        TOBEVALUATE = 4, _('待评价')
        COMPLETE = 5, _('已完成')
        CANCELLED = 6, _('已取消')

    owner = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="用户")
    order_sn = models.CharField(
        blank=True, default="",
        unique=True, max_length=32,
        verbose_name="订单号", help_text="订单号")
    trade_sn = models.CharField(
        blank=True, null=True,
        unique=True, max_length=64,
        verbose_name="交易号", help_text="交易号")
    pay_status = models.IntegerField(
        choices=OrderStatusChoices.choices, default=1, verbose_name="支付状态", help_text="支付状态")
    pay_method = models.IntegerField(
        choices=PayMethodChoices.choices, default=2, verbose_name="支付方式", help_text="支付方式")
    total_amount = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="商品总金额")
    order_mark = models.CharField(
        blank=True, default="", max_length=100, verbose_name="订单备注", help_text="订单备注")
    freight = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="运费")
    address = models.CharField("地址", max_length=150)
    pay_time = models.DateTimeField(
        null=True, blank=True, verbose_name="支付时间", help_text="支付时间")

    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_sn

    @classmethod
    def get_pay_method(cls):
        # 支付方式列表字典
        return dict(cls.PayMethodChoices.choices)

    @classmethod
    def get_pay_default(cls):
        # 获取支付方式的默认值
        return cls._meta.get_field('pay_method').default


class DJMallOrderProduct(DJMallBaseModel):
    """订单商品"""
    order = models.ForeignKey(DJMallOrderInfo, on_delete = models.CASCADE, verbose_name="订单")
    sku = models.ForeignKey(DJMallProductSKU, on_delete = models.PROTECT, blank=True, null=True, verbose_name="订单商品")
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField('单价', max_digits=5, decimal_places=2)
    is_commented = models.BooleanField(default=False,verbose_name="是否已评价")

    class Meta:
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name
    
    def __str__(self) -> str:
        return self.sku.spu.title

DjangoMall/apps/order/forms.py
from django import forms
from django.forms import ModelForm
from django.core.cache import cache
from order.models import DJMallOrderInfo, DJMallOrderProduct
from users.models import DJMallAddress


class DJMallOrderInfoForm(ModelForm):
    # 订单表单
    # address_data = forms.ModelMultipleChoiceField(queryset=None, widget=forms.Select)
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        # self.fields['address_data'].queryset = DJMallAddress.objects.filter(owner=user)
        # print()
    
    class Meta:
        model = DJMallOrderInfo
        fields = ['pay_method', 'order_mark', 'address',]

    
class DJMallOrderProductForm(ModelForm):
    
    # sku = forms.ModelMultipleChoiceField(queryset=None, widget=forms.Select)
    
    def __init__(self, *args, **kwargs):
        # print(kwargs)
        super().__init__(*args, **kwargs)
        # self.fields['sku'].queryset = D.objects.all()
        print(kwargs)
    
    # 订单商品表单
    class Meta:
        model = DJMallOrderProduct
        fields = ['order', 'sku',]
        

DjangoMall/apps/order/views.py
import json
from decimal import Decimal
from xmlrpc.client import Boolean
from django.http import JsonResponse
from django.shortcuts import render
from django.core.cache import cache
from django.utils import timezone
from django.views.generic import TemplateView
from personal.views import DJMallLoginRequiredMixin
from DJMall.utils.views import DJMallBaseView
# Create your views here.
from users.models import DJMallAddress
from product.models import DJMallProductSKU
from .models import DJMallOrderInfo, DJMallOrderProduct


class DJMallPayView(DJMallLoginRequiredMixin, DJMallBaseView, TemplateView):
    """支付视图"""
    http_method_names = ['get', 'post']
    template_name = 'order/pay.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pay_method'] = DJMallOrderInfo.get_pay_method()
        context['pay_default'] = DJMallOrderInfo.get_pay_default()
        context['address_list'] = DJMallAddress.objects.filter(owner=self.request.user)
        context['carts'] = self.get_carts()
        context['type'] = self.get_type()
        return context
    
    def post(self, request, *args, **kwargs):
        # 获取到购物车数据放入缓存，永不过期，支付完成后主动清除缓存
        data = request.POST
        
        #  第一次POST请求购物车点击去支付按钮时传送的数据并缓存 #
        #####################################################
        # @is_type 拥有两个值
        # -- cache 为缓存标识，可以将其缓存
        # -- cart  为支付标识，代表支付的商品数据来自购物车
        is_type = data.get('type')
        carts = data.get('carts')
        # 缓存时机判断，这里如果不做判断，两次POST会覆盖缓存
        if is_type == 'cache' and carts:
            cache.set(request.user.id, carts, timeout=None) 
        ######################################################
        
        # 第二次type为cart表明为购物车数据支付    
        if is_type == 'cart' and self.get_carts():
            pay_method = data.get('pay_method')
            order_mark = data.get('order_mark')
            address = DJMallAddress.objects.get(id=data.get('address')).address
            # 商品总金额，不含运费
            total_amount = self.get_sku_total_price(json.loads(self.get_carts()))
            # 订单号
            order_sn = self.get_order_sn()
            order = DJMallOrderInfo.objects.create(
                owner=request.user,
                order_sn=order_sn,
                pay_method=pay_method,
                total_amount=total_amount,
                address = address,
                order_mark = order_mark,
                freight = 0
            )
            for cart in json.loads(self.get_carts()):
                sku = DJMallProductSKU.objects.get(id=int(cart.get('sku__id')))
                DJMallOrderProduct.objects.create(
                    order = order,
                    sku = sku,
                    count = int(cart.get('num')),
                    price = Decimal(cart.get('sku__sell_price'))
                )
            
        return JsonResponse({'message': 'ceshi'})
    
    def get_carts(self):
        """从缓存中读取购物车信息
        开发时使用内存缓存：每次服务器重载缓存信息会丢失
        部署时建议使用redis
        Returns:
            [type]: [{}]购物车数据
        """
        # 如果缓存在内存中，那么从缓存中读取购物车信息
        carts = cache.get(self.request.user.id)
        if carts:
            return carts
        else:
            return []
        
    def get_order_sn(self):
        # 生成订单号
        order_sn = timezone.now().strftime('%Y%m%d%H%M%S') + '%09d' % self.request.user.id
        return order_sn
    
    def get_sku_total_price(self, carts):
        """计算商品总金额，不含运费

        Args:
            carts (list): [购物车选中结算的数据列表]

        Returns:
            [float]: [商品总价金额，保留两位小数]
        """
        sku_total_price = [ Decimal(cart.get('sku__sell_price')) * cart.get('num') for cart in carts ]
        return sum(sku_total_price)
    
    def get_type(self):
        # 获取get请求中携带的类型
        cart = self.request.GET.get('type')
        if cart:
            return cart

DjangoMall/apps/order/views/order.py
from django.http import HttpResponse
from django.views.generic import CreateView, View
from django.urls import reverse_lazy
from django.core.cache import cache
from django.utils import timezone

from order.models import DJMallOrderInfo
from personal.views import DJMallLoginRequiredMixin
from DJMall.utils.views import DJMallBaseView
from users.models import DJMallAddress
from order.forms import DJMallOrderInfoForm, DJMallOrderProductForm


# class DJMallOrderInfoView(DJMallLoginRequiredMixin, DJMallBaseView, CreateView):
    
#     model = DJMallOrderInfo
#     # template_name = 'order/orderinfo.html'
#     template_name = 'order/pay.html'
#     form_class = DJMallOrderInfoForm
#     success_url = reverse_lazy('author-list')
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['pay_method'] = DJMallOrderInfo.get_pay_method()
#         context['pay_default'] = DJMallOrderInfo.get_pay_default()
#         context['address_list'] = DJMallAddress.objects.filter(owner=self.request.user)
#         context['product_form'] = DJMallOrderProductForm()
#         context['carts'] = cache.get(self.request.user.id)
#         print(context['carts'])       
#         return context
    
#     def form_valid(self, form):
#         form.instance.owner = self.request.user
#         form.instance.order_sn = self.get_order_sn()
#         address = form.cleaned_data['address']
#         print(self.request.POST.get('address'))
#         # form.instance.address = form.cleaned_data['address']
#         # return super().form_valid(form)
#         return HttpResponse('ceshi')
    
#     def get_order_sn(self):
#         # 生成订单号
#         order_sn = timezone.now().strftime('%Y%m%d%H%M%S') + '%09d' % self.request.user.id
#         return order_sn

#     def get_form_kwargs(self):
#         # 向表单中传递数据
#         kwargs = super().get_form_kwargs()
#         kwargs['user'] = self.request.user
#         return kwargs


class DJMallOrderInfoView(DJMallLoginRequiredMixin, DJMallBaseView, View):
    pass

DjangoMall/apps/order/views/views.py
import json
from decimal import Decimal
from django.db.models import F
from django.forms import ValidationError
from django.http import JsonResponse
from django.shortcuts import render
from django.core.cache import cache
from django.utils import timezone
from django.views.generic import TemplateView
from personal.views import DJMallLoginRequiredMixin
from DJMall.utils.views import DJMallBaseView
from config.conf import DEL_STOCK_TIMING

# Create your views here.
from users.models import DJMallAddress
from product.models import DJMallProductSKU
from order.models import DJMallOrderInfo, DJMallOrderProduct


class DJMallPayView(DJMallLoginRequiredMixin, DJMallBaseView, TemplateView):
    """支付视图"""
    http_method_names = ['get', 'post']
    template_name = 'order/pay.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pay_method'] = DJMallOrderInfo.get_pay_method()
        context['pay_default'] = DJMallOrderInfo.get_pay_default()
        context['address_list'] = DJMallAddress.objects.filter(owner=self.request.user)
        context['carts'] = self.get_carts()
        context['type'] = self.get_type()
        return context
    
    def post(self, request, *args, **kwargs):
        """获取到购物车数据并存入缓存，不过期，待支付完成后清除缓存
        # is_type 拥有两个值
        -- cache 为缓存标识，第一次post将缓存
        -- cart  为支付标识， 代表支付的商品数据来自购物车
        
        缓存购物车数据时机为，当post过来的is_type带有cache标识和购物车数据存在时则缓存
        
        支付时机为，当post传过来的is_type的类型为cart并且缓存中有购物车商品数据时则创建订单支付
    
        """
        # 获取到购物车数据放入缓存，永不过期，支付完成后主动清除缓存
        data = request.POST
        
        #  第一次POST请求购物车点击去支付按钮时传送的数据并缓存 #
        #####################################################
        # @is_type 拥有两个值
        # -- cache 为缓存标识，可以将其缓存
        # -- cart  为支付标识，代表支付的商品数据来自购物车
        is_type = data.get('type')
        carts = data.get('carts')
        # 缓存时机判断，这里如果不做判断，两次POST会覆盖缓存
        if is_type == 'cache' and carts:
            cache.set(request.user.id, carts, timeout=None) 
        ######################################################
        
        # 第二次type为cart表明为购物车数据支付    
        if is_type == 'cart' and self.get_carts():
            pay_method = data.get('pay_method')
            order_mark = data.get('order_mark')
            # address = DJMallAddress.objects.get(id=data.get('address')).address
            address = data.get('address')
            print(address)
            # 商品总金额，不含运费
            total_amount = self.get_sku_total_price(json.loads(self.get_carts()))
            # 订单号
            order_sn = self.get_order_sn()
            order = DJMallOrderInfo.objects.create(
                        owner=request.user,
                        order_sn=order_sn,
                        pay_method=pay_method,
                        total_amount=total_amount,
                        address=address,
                        order_mark=order_mark,
                        freight=0
                    )
            for cart in json.loads(self.get_carts()):
                sku = DJMallProductSKU.objects.get(id=int(cart.get('sku__id')))
                if sku.stocks > int(cart.get('num')):  # 减库存
                    self.del_stock(sku, int(cart.get('num')))
                    DJMallOrderProduct.objects.create(
                        order = order,
                        sku = sku,
                        count = int(cart.get('num')),
                        price = Decimal(cart.get('sku__sell_price'))
                    )
                else:
                    return JsonResponse({'code': 'err', 'message': f'{sku}的库存不足！'})
                    # return render(request, 'order/pay.html', {'sku': sku})
                
        return JsonResponse({'message': 'ceshi'})
    
    def get_carts(self):
        """从缓存中读取购物车信息
        开发时使用内存缓存：每次服务器重载缓存信息会丢失
        部署时建议使用redis
        Returns:
            [type]: [{}]购物车数据
        """
        # 如果缓存在内存中，那么从缓存中读取购物车信息
        carts = cache.get(self.request.user.id)
        if carts:
            return carts
        else:
            return []
        
    def get_order_sn(self):
        # 生成订单号
        order_sn = timezone.now().strftime('%Y%m%d%H%M%S') + '%09d' % self.request.user.id
        print(order_sn)
        return order_sn
    
    def get_sku_total_price(self, carts):
        """计算商品总金额，不含运费

        Args:
            carts (list): [购物车选中结算的数据列表]

        Returns:
            [float]: [商品总价金额，保留两位小数]
        """
        sku_total_price = [ Decimal(cart.get('sku__sell_price')) * cart.get('num') for cart in carts ]
        return sum(sku_total_price)
    
    def get_type(self):
        # 获取get请求中携带的类型
        cart = self.request.GET.get('type')
        return cart
        
    def del_stock(self, sku, num, time=DEL_STOCK_TIMING):
        # 减库存操作
        # time为0时加购减库存
        if time:
            sku.stocks = F('stocks') - int(num)
            sku.save()
            
                          

DjangoMall/themes/default/templates/order/orderinfo.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  订单页面
{% endblock %}

{% block breadcrumb %}
<li class="is-active"><a href=""><span>支付页</span></a></li>
{% endblock %}


{% block main %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <!-- {{ product_form.as_p }} -->
    <input type="submit" value="提交">
</form>
{% endblock %}

DjangoMall/themes/default/templates/order/pay.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  支付页面
{% endblock %}
{% block head_style %}
<link rel="stylesheet" href="{% static 'order/css/order.css' %}">
{% endblock %}

{% block breadcrumb %}
<li class="is-active"><a href=""><span>支付页</span></a></li>
{% endblock %}

{% block main %}
<div class="section" id="pay">
    <section class="container">  
        
    <form id="form" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="type" value="{{ type }}">
        <!-- 支付方式 -->
        <div class="card is-shadowless">
            <header class="card-header">
                <p class="card-header-title">
                    支付方式
                </p>
            </header>
            <div class="card-content">
                <div class="columns is-multiline">
                    {% for key, value in pay_method.items %}
                    <div class="column is-3">
                    <label class="address">
                        <input type="radio" name="pay_method" id="pay_method_{{ key }}" value="{{ key }}" {% if pay_default == key %}checked{% endif %} hidden>
                        <div class="box attr is-shadowless border has-text-centered">
                            {{ value }}
                        </div>
                    </label>
                    </div>
                    {% endfor %}
                </div>
        
            </div>
        </div>
        <!-- 支付方式 end-->

        <!-- 收货地址 -->
        <div class="card mt-3 is-shadowless">
            <header class="card-header">
                <p class="card-header-title">
                    收货地址
                </p>
            </header>
            <div class="card-content">

                <div class="columns is-multiline">
                    {% if address_list %}
                    {% for addr in address_list %}
                    <div class="column is-6">
                        <label class="address">
                            <input type="radio" name="address" id="address_{{ addr.id }}" value="{{ addr.address }}" {% if addr.is_default %}checked{% endif %} hidden>
                            <div class="box attr is-shadowless border">
                                {% if addr.is_default %}
                                <span class="tag is-primary">默认</span>
                                {% endif %}
                                {{ addr.name }}{{ addr.phone }}
                                <p class="has-text-grey-dark">
                                    {{ addr.address }}
                                </p>
                            </div>
                        </label>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="column is-6">
                        <a class="box has-text-grey-light has-text-centered is-shadowless" 
                            style="cursor: pointer; border: solid 1px rgb(236, 235, 235);" href="{% url 'personal:address_create' %}">
                            <div class="pt-2 pb-2">
                                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                                    <path fill="currentColor" d="M13 20H13.09A5.5 5.5 0 0 0 13.81 22H9A2 2 0 0 1 11 20V12H3.5L6 9.5L3.5 7H11V3L12 2L13 3V7H18L20.5 9.5L18 12H13M18 15V18H15V20H18V23H20V20H23V18H20V15Z" />
                                </svg>
                                <span>添加新地址</span>
                            </div>
                        </a>
                    </div> 
                </div>
            </div>
        </div>
        <!-- 收货地址 end -->

        <!-- 订单商品信息 -->
        <div class="box is-shadowless has-background-white mt-4" v-if="cartJson.length">
            <div id="cartJson" v-show='show'>{{ carts }}</div>
            <h1 class="is-size-5 mb-2">订单信息:</h1>
            <div class="box is-shadowless border mt-3">
                <div class="level" v-for="(item, index) in cartJson" :key="index">
                    <div class="level-left">
                        <div class="level-item">
                            <figure class="image">
                                <img :src="item.sku__main_picture" alt="" style="width: 100px;">
                            </figure>
                        </div>
                        <div class="level-item" style="display: block;">
                            <h1>[[ item.sku__spu__title ]]</h1>
                            <p class=" has-text-grey mt-2">[[ item.sku_options ]]</p>
                        </div>
                        
                    </div>
                    <div class="level-right">
                        <div class="level-item pr-6">
                            [[ item.num ]] x [[ item.sku__sell_price ]]
                        </div>
                        <div class="level-item pl-5">
                            <strong class="has-text-danger-dark is-size-5">[[ item.sku_total_price ]]</strong>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box is-shadowless has-background-white mt-4" v-else>未查询到任何商品信息，请前往选购商品！</div>
        <!-- 订单商品信息 end -->
        <div class="box has-text-right is-shadowless">
            <div class="columns">
                <div class="column is-10">
                    <ul>
                        <li>
                        共[[ cartJson.length ]] 件商品,总商品金额：</li>
                        <li>运费：</li>
                    </ul>
                </div>
                <div class="column">
                    <ul>
                        <li class=" has-text-right ">¥[[ totalPrice|numFilter ]]</li>
                        <li class=" has-text-right ">¥[[ freight|numFilter ]]</li>
                    </ul>
                </div>
            </div>

            <div class="columns has-background-light">
                <div class="column is-10">
                    <label style="line-height: 2.5em;">应付总金额：</label>
                </div>
                <div class="column">
                    <span class="is-size-4 has-text-weight-bold has-text-danger-dark">
                        ¥[[toTal]]
                    </span>
                </div>
            </div>
        </div>
        <b-field label="订单备注" :label-position="labelPosition">
            <b-input 
                maxlength="200" 
                type="textarea" 
                placeholder="有特殊要求，请务必备注说明!" 
                name="order_mark" 
                id="id_order_mark">
            </b-input>
        </b-field>
        <input class="button is-primary is-pulled-right pl-6 pr-6" type="submit" value="立即支付">
        <div class="is-clearfix"></div>
    </form>
    </section>
</div>

{% endblock %}

{% block vue_script %}
<script>
    var cartJson = JSON.parse(document.querySelector('#cartJson').innerHTML);
    // console.log(cartJson)
    var type = '{{ type }}';

    var pay = new Vue({
        el: '#pay',
        // 修改Vue变量的读取语法，避免与django冲突
        delimiters: ['[[', ']]'],
        data: {
            labelPosition: 'on-border',
            cartJson: cartJson,
            freight: 0,
            show: false,
            type: type
        },
        filters: {
            numFilter (value) {
                let realVal = ''
                if (!isNaN(value) && value!== '') {
                    // 截取当前数据到小数点后两位
                    realVal = parseFloat(value).toFixed(2)
                } else {
                    realVal = '-'
                }
                return realVal
            }
        },
        computed: {
            // 商品总价
            totalPrice: function(){
                var total = 0;
                this.cartJson.forEach((element, i, arr) => {
                    total += parseFloat(arr[i].sku_total_price)
                }) 
                return total;
            },
            // 总价
            toTal: function(){
                return (this.totalPrice + this.freight).toFixed(2);
            }
            
        },

        methods: {
            getPay(){
                console.log('ceshi')
            }
        }
        
    })
</script>
{% endblock %}